"""empty message

Revision ID: 40be9568e633
Revises: 2d408f2ecdc6
Create Date: 2022-07-07 12:28:00.102572

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '40be9568e633'
down_revision = '2d408f2ecdc6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('relationships_status_key', 'relationships', type_='unique')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('relationships_status_key', 'relationships', ['status'])
    # ### end Alembic commands ###
